
# --- COLORES ---
COLOR_FONDO = "#f5f5f5"
COLOR_CAJA = "#4682b4"           # Azul acero
COLOR_CAJA_EXPRESS = "#dc143c"   # Rojo carmesí
COLOR_PERSONA = "#3c3c3c"
COLOR_TEXTO = "#000000"
COLOR_PANEL = "#ffffff"
COLOR_BOTON = "#2196F3"
COLOR_BOTON_HOVER = "#1976D2"

# --- DIMENSIONES DE PANTALLA ---
ANCHO_PANTALLA = 1200
ALTO_PANTALLA = 750

# --- PARÁMETROS DE SIMULACIÓN ---
TIEMPO_ESCANEO_NORMAL = 5   # seg por artículo
TIEMPO_ESCANEO_EXPRESS = 5  # seg por artículo

TIEMPO_COBRO_MIN = 15  # seg
TIEMPO_COBRO_MAX = 30  # seg

ARTICULOS_MIN = 1
ARTICULOS_MAX_NORMAL = 50
ARTICULOS_MAX_EXPRESS = 10

# --- VELOCIDAD DE SIMULACIÓN ---
VELOCIDAD_SIMULACION = 10.0  # Multiplicador de velocidad
